/**
 * Complete Google Sheets Schema Definitions for Pharmacy ERP
 * Matches the specification precisely.
 */

export interface SheetDefinition {
  sheetName: string;
  columns: string[];
  description: string;
}

export const PHARMACY_SHEETS: Record<string, SheetDefinition> = {
  Company: {
    sheetName: 'Company',
    description: 'Pharmacy business identity, legal and localization profile',
    columns: [
      'company_id',
      'company_name',
      'legal_name',
      'pharmacy_name',
      'owner_name',
      'phone',
      'email',
      'address',
      'city',
      'province',
      'country',
      'ntn',
      'strn',
      'logo_url',
      'currency',
      'timezone',
      'created_at',
      'updated_at',
    ],
  },
  Users: {
    sheetName: 'Users',
    description: 'System operators and authorized personnel',
    columns: [
      'user_id',
      'employee_id',
      'name',
      'email',
      'phone',
      'role',
      'status',
      'last_login',
      'created_at',
      'updated_at',
    ],
  },
  Roles: {
    sheetName: 'Roles',
    description: 'Role-based access control definitions and permission sets',
    columns: [
      'role_id',
      'role_name',
      'description',
      'permissions',
      'status',
    ],
  },
  Products: {
    sheetName: 'Products',
    description: 'Medicines, OTC, supplements, and clinical inventory items',
    columns: [
      'product_id',
      'barcode',
      'sku',
      'product_name',
      'generic_name',
      'brand_name',
      'category',
      'manufacturer',
      'dosage_form',
      'strength',
      'pack_size',
      'unit',
      'purchase_price',
      'sale_price',
      'retail_price',
      'tax_rate',
      'reorder_level',
      'prescription_required',
      'controlled_medicine',
      'status',
      'created_at',
      'updated_at',
    ],
  },
  Categories: {
    sheetName: 'Categories',
    description: 'Product classifications and clinical groupings',
    columns: [
      'category_id',
      'category_name',
      'description',
      'status',
    ],
  },
  Batches: {
    sheetName: 'Batches',
    description: 'FEFO batch records with manufacturing and expiration dates',
    columns: [
      'batch_id',
      'product_id',
      'batch_number',
      'manufacturing_date',
      'expiry_date',
      'purchase_price',
      'sale_price',
      'quantity',
      'remaining_quantity',
      'supplier_id',
      'purchase_invoice_id',
      'created_at',
      'updated_at',
    ],
  },
  Suppliers: {
    sheetName: 'Suppliers',
    description: 'Distributors, pharmaceutical manufacturers, and vendors',
    columns: [
      'supplier_id',
      'supplier_name',
      'contact_person',
      'phone',
      'email',
      'address',
      'city',
      'ntn',
      'strn',
      'payment_terms',
      'credit_limit',
      'opening_balance',
      'status',
      'created_at',
      'updated_at',
    ],
  },
  Customers: {
    sheetName: 'Customers',
    description: 'Patients, regular clients, and corporate accounts',
    columns: [
      'customer_id',
      'customer_code',
      'customer_name',
      'phone',
      'email',
      'address',
      'city',
      'date_of_birth',
      'gender',
      'customer_type',
      'opening_balance',
      'credit_limit',
      'status',
      'created_at',
      'updated_at',
    ],
  },
  Purchases: {
    sheetName: 'Purchases',
    description: 'Stock purchase invoices received from suppliers',
    columns: [
      'purchase_id',
      'invoice_number',
      'supplier_id',
      'purchase_date',
      'subtotal',
      'discount',
      'tax',
      'total',
      'paid_amount',
      'remaining_amount',
      'payment_method',
      'status',
      'created_by',
      'created_at',
    ],
  },
  Purchase_Items: {
    sheetName: 'Purchase_Items',
    description: 'Line items within purchase invoices',
    columns: [
      'purchase_item_id',
      'purchase_id',
      'product_id',
      'batch_number',
      'manufacturing_date',
      'expiry_date',
      'quantity',
      'free_quantity',
      'purchase_price',
      'sale_price',
      'discount',
      'tax',
      'total',
    ],
  },
  Sales: {
    sheetName: 'Sales',
    description: 'POS sales invoices issued to customers',
    columns: [
      'sale_id',
      'invoice_number',
      'customer_id',
      'sale_date',
      'subtotal',
      'discount',
      'tax',
      'total',
      'paid_amount',
      'remaining_amount',
      'payment_method',
      'sale_type',
      'status',
      'created_by',
      'created_at',
    ],
  },
  Sale_Items: {
    sheetName: 'Sale_Items',
    description: 'Line items associated with POS sales and batch deduction',
    columns: [
      'sale_item_id',
      'sale_id',
      'product_id',
      'batch_id',
      'quantity',
      'sale_price',
      'discount',
      'tax',
      'total',
    ],
  },
  Returns: {
    sheetName: 'Returns',
    description: 'Sales returns and credit refunds against past invoices',
    columns: [
      'return_id',
      'return_number',
      'original_invoice_id',
      'customer_id',
      'return_date',
      'reason',
      'total',
      'refund_amount',
      'created_by',
      'created_at',
    ],
  },
  Expenses: {
    sheetName: 'Expenses',
    description: 'Operational expenses, rent, utilities, and pharmacy overhead',
    columns: [
      'expense_id',
      'expense_date',
      'category',
      'description',
      'amount',
      'payment_method',
      'employee_id',
      'notes',
      'created_at',
    ],
  },
  Payments: {
    sheetName: 'Payments',
    description: 'Cash inflows and outflows across sales, purchases, and expenses',
    columns: [
      'payment_id',
      'reference_type',
      'reference_id',
      'party_type',
      'party_id',
      'amount',
      'payment_method',
      'payment_date',
      'notes',
      'created_by',
    ],
  },
  Stock_Adjustments: {
    sheetName: 'Stock_Adjustments',
    description: 'Inventory write-offs, damages, corrections, and audit adjustments',
    columns: [
      'adjustment_id',
      'product_id',
      'batch_id',
      'adjustment_type',
      'quantity',
      'reason',
      'reference',
      'created_by',
      'created_at',
    ],
  },
  Employees: {
    sheetName: 'Employees',
    description: 'Pharmacy staff, pharmacists, technicians, and cashiers',
    columns: [
      'employee_id',
      'employee_code',
      'name',
      'cnic',
      'phone',
      'email',
      'designation',
      'department',
      'joining_date',
      'salary',
      'status',
      'created_at',
    ],
  },
  Audit_Logs: {
    sheetName: 'Audit_Logs',
    description: 'Immutable trail of critical system events and transaction changes',
    columns: [
      'log_id',
      'user_id',
      'action',
      'module',
      'record_id',
      'old_value',
      'new_value',
      'timestamp',
    ],
  },
};

export const ORDERED_SHEET_NAMES = [
  'Company',
  'Users',
  'Roles',
  'Products',
  'Categories',
  'Batches',
  'Suppliers',
  'Customers',
  'Purchases',
  'Purchase_Items',
  'Sales',
  'Sale_Items',
  'Returns',
  'Expenses',
  'Payments',
  'Stock_Adjustments',
  'Employees',
  'Audit_Logs',
];
